In [2]:
import numpy as np
import os
import matplotlib.pyplot as plt
%matplotlib

Using matplotlib backend: TkAgg


In [3]:
# csvfile = "/home/zhaoliang/Documents/ndnSIM/ndnSIM-scenario-template/data/u-ips2.csv"
csvfile = "/home/zhaoliang/Documents/ndnSIM/ndnSIM-scenario-template/data/u-ips2.csv"

with open(csvfile, 'r') as f:
    data = []
    lines = f.readlines()
    for line in lines:
        l = map(lambda x: float(x),line.rstrip().split(","))
#         l = line.rstrip().split(",")
#         print l
        if l not in data:
            data.append(l)
#     print data
    npdata = np.array(data)
    npdata = npdata.transpose()

In [68]:
datafile = "/home/zhaoliang/Documents/ndnSIM/ndnSIM-scenario-template/data/simu7/abw-1mbpsbn-0.5mbpsct.txt"
with open(datafile, 'r') as f:
    data = []
    lines = f.readlines()
    for line in lines:
        l = line.rstrip().split("\t")
        if len(l) != 2:
            continue
        data.append(l)
    npdata = np.array(data)
    npdata = npdata.transpose()

In [129]:
def model(u):
    abw = 0.7
    c = 2.0
    if u < abw:
        return 0
    else: 
        return ((1/c) * u - (abw/c))

In [128]:
print model(1.7)

0.5
0.5


In [18]:
t = 0
a=np.array([100,-1])
p=np.array([[10.0,0],
             [0,1]])
# u=np.array([-float(a[1])/float(a[0]),1])
# y = np.zeros(100)
H = 0.001 #观测误差var
Q = np.array([[0.001,0],[0,0.001]])
for uips in npdata.transpose():
    ips = float(uips[1])
    u0 = float(uips[0])
    if ips == 0:
        continue;
    u = np.array([u0, 1],[])
    v = ips - np.matmul(u,np.transpose(a))
#     print v
#     f = np.matmul(np.matmul(np.transpose(u), p), u) + H
    f = np.matmul(np.matmul(u, p), np.transpose(u)) + H
    k = np.matmul(p,np.transpose(u)) * float(1/f)
#     print k
#     ppost = p - np.matmul((k.T * f), k) #??
    ahat = a + k * v
    print a, k ,v
#     phat = p - np.matmul(k, u) * p #??
    phat = p - np.matmul(k * f , np.transpose(k))#??
    a = ahat
    p = phat + Q
    print -float(a[1])/float(a[0])
#     print p
    t = t + 1

[100  -1] [ 0.89146113  0.08705675] -101.3508197
1.01798907032
[ 9.64968418 -9.82327303] [ 0.32026701  0.67208466] 0.0267422269709
1.0152254468
[ 9.65824883 -9.80529999] [ 0.60988065  0.33642218] -0.580067743649
1.07479957421
[  9.30447674 -10.00044764] [ 0.36147921  0.60673544] 0.0200339451811
1.0726583103
[ 9.3117186  -9.98829234] [ 0.56071698  0.3540344 ] -0.553622487644
1.13142563644
[  9.00129307 -10.18429374] [ 0.37202737  0.57144343] 0.0223511238109
1.12896376838
[  9.0096083  -10.17152134] [ 0.52853991  0.35728012] -0.529260354978
1.18680024891
[  8.72987308 -10.36061554] [ 0.37387859  0.545379  ] 0.0250898789881
1.18396060662
[  8.73925365 -10.34693205] [ 0.50353864  0.355458  ] -0.53319061903
1.24386058964
[  8.47077157 -10.53645892] [ 0.37197713  0.52388214] 0.0272043101507
1.2406959514
[  8.48089095 -10.52220707] [ 0.48261371  0.35135663] -0.514408371103
1.30006417298
[  8.23263042 -10.70294786] [ 0.36817056  0.50518977] 0.0605145738687
1.2928519365
[  8.25491011 -10.672376

In [4]:
# print npdata.transpose
print npdata
plt.plot(npdata[0],npdata[1])

[[ 0.064      0.128      0.192      0.256      0.32       0.384      0.448
   0.512      0.576      0.64       0.704      0.768      0.832      0.896
   1.024      1.024      1.088      1.088      1.152      1.152      1.216
   1.216      1.28       1.28       1.344      1.344      1.408      1.408
   1.472      1.472      1.536      1.536      1.6        1.6        1.664
   1.664      1.728      1.792      1.792      1.856      1.856      1.92
   1.92       1.984      2.048      2.048      1.024    ]
 [ 0.         0.         0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.         0.0491803
   0.0847458  0.122807   0.142857   0.185185   0.207547   0.254902   0.28
   0.306122   0.333333   0.361702   0.422222   0.454545   0.488372
   0.488372   0.52381    0.560976   0.6        0.641026   0.684211
   0.684211   0.72973    0.777778   0.828571   0.882353   0.882353
   0.939394   0.939394   1.         1.06452    1.06452  

In [131]:
from numpy.linalg import inv
t = 0
a=np.array([100,-1])
p=np.array([[10.0,0],
             [0,1]])
# # u=np.array([-float(a[1])/float(a[0]),1])
# # y = np.zeros(100)
H = np.array([[0.001,0],[0,0.001]]) #观测误差var
Q = np.array([[0.001,0],[0,0.001]])
data = npdata.transpose()[1:].reshape(23,2,2)
for pair in data:
    
    u = np.array([[pair[0][0], 1],[pair[1][0], 1]])
#     ips = [pair[0][1],pair[1][1]]
#     print u
    ips = [model(pair[0][0]),model(pair[1][0])]
    if ips[0] == 0:
        continue;
    v = ips - np.matmul(u,np.transpose(a))
#     print v
    
    f = np.matmul(np.matmul(u, p),np.transpose(u)) + H
#     print f
#     f = np.matmul(np.matmul(u, p), np.transpose(u)) + H
    
    k = np.matmul(np.matmul(p,np.transpose(u)), np.linalg.inv(f))
#     print k
#     ppost = p - np.matmul((k.T * f), k) #??
    ahat = a + np.matmul(k, v)
#     print a, k ,v
# #     phat = p - np.matmul(k, u) * p #??
    phat = p - np.matmul(np.matmul(k,f), np.transpose(k))#??
    a = ahat
    p = phat + Q
#     print a
    print -float(a[1])/float(a[0]),1/float(a[0])
#     print p
#     t = t + 1

0.787974602495 0.234977983931
0.818730477477 0.97785012227
0.84349622473 1.14361293989
0.857954613823 1.22314162886
0.869161147076 1.28394717696
0.878620958576 1.33512278136
0.886792821016 1.37935457876
0.893917778963 1.41809662995
0.900165575656 1.45236593551
0.905667441881 1.48292923186
0.910528286039 1.51038129077
0.914833581836 1.53519187238
0.918653984348 1.55773752138
0.927658364555 1.57905852656
0.93446365506 1.59186286264
0.94070508372 1.60330665922
0.944622996969 1.62583940313
0.73226125835 1.93543469863


In [144]:
a=np.array([100,-1])
p=np.array([[10.0,0],
             [0,1]])
# # u=np.array([-float(a[1])/float(a[0]),1])
# # y = np.zeros(100)
H = np.array([[0.001,0],[0,0.001]]) #观测误差var
Q = np.array([[0.001,0],[0,0.001]])
for i in range(0,100):
    u1 = np.random.uniform(0.7,2,2)
    u = np.array([[u1[0], 1],[u1[1],1]])
    
#     ips = [pair[0][1],pair[1][1]]
#     print u
    ips = [model(u1[0]),model(u1[1])]
    if ips[0] == 0:
        continue;
    v = ips - np.matmul(u,np.transpose(a))
#     print v
    
    f = np.matmul(np.matmul(u, p),np.transpose(u)) + H
#     print f
#     f = np.matmul(np.matmul(u, p), np.transpose(u)) + H
    
    k = np.matmul(np.matmul(p,np.transpose(u)), np.linalg.inv(f))
    print k
#     ppost = p - np.matmul((k.T * f), k) #??
    ahat = a + np.matmul(k, v)
#     print a, k ,v
# #     phat = p - np.matmul(k, u) * p #??
    phat = p - np.matmul(np.matmul(k,f), np.transpose(k))#??
    a = ahat
    p = phat + Q
#     print a
    print -float(a[1])/float(a[0]),1/float(a[0])

[[ -7.1842583    7.41181712]
 [ 10.65901782  -9.98130876]]
1.25549142727 0.444626451421
[[-1.73953217  1.25352784]
 [ 2.357016   -0.94607476]]
0.742269370017 1.80805826449
[[-0.31348727  0.83731534]
 [ 0.89171226 -0.85514166]]
0.74024176382 1.9100996556
[[ 0.63803061 -0.53892647]
 [-0.41152375  1.13840341]]
0.714925396378 1.96331000941
[[-0.32455015  0.5378075 ]
 [ 0.83368028 -0.2868731 ]]
0.70893973869 1.9791016128
[[-0.12976607  0.44564771]
 [ 0.5623958  -0.12898019]]
0.70671493804 1.98078657543
[[-0.12524789  0.46701655]
 [ 0.55410668 -0.1449245 ]]
0.705546168924 1.98265004846
[[ 0.54826397 -0.22319781]
 [-0.33260256  0.70903536]]
0.704843722004 1.98836409738
[[-0.11340405  0.46253935]
 [ 0.57397743 -0.24727692]]
0.704386726808 1.99026438305
[[ 0.53094701 -0.38162263]
 [-0.25073904  0.8958614 ]]
0.701980759971 1.99536218003
[[ 0.24634373  0.15172448]
 [ 0.07858948  0.20335789]]
0.701912267271 1.99529332313
[[-0.2620469   0.52461636]
 [ 0.72104964 -0.21070588]]
0.701261000302 1.99624

In [136]:
print  [np.random.uniform(0,2,1) ,1]

[array([ 0.8982587]), 1]
